config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :pics do
    member do
      put 'like', to: 'pics#upvote'
    end
  end

  root 'pics#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pic.rb
class Pic < ApplicationRecord
  acts_as_votable

  belongs_to :user

  has_attached_file :image, styles: { medium: '300x300>', thumb: '100x100>' }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pics

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  before_action :find_pic, only: %i[show edit update destroy upvote]
  before_action :authenticate_user!, except: %i[index show]
  before_action :correct_user, only: %i[edit update destroy]

  def index
    @pics = Pic.all.order('created_at DESC')
  end

  def show
  end

  def new
    @pic = current_user.pics.build
  end

  def create
    @pic = current_user.pics.build(pic_params)

    if @pic.save
      redirect_to @pic, notice: 'Yesss! It was posted!'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @pic.update(pic_params)
      redirect_to @pic, notice: 'Congrats! Pic was update'
    else
      render 'edit'
    end
  end

  def destroy
    @pic.destroy
    redirect_to root_path
  end

  def upvote
    @pic.upvote_by current_user
    redirect_to @pic
  end

  private

  def correct_user
    flash[:notice] = 'Access denied as you are not owner of this Pic'
    redirect_to @pic if current_user != @pic.user
  end

  def find_pic
    @pic = Pic.find(params[:id])
  end

  def pic_params
    params.require(:pic).permit(:title, :description, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagramm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div clas="container">
        <div class="navbar-brand">
          <%= link_to 'Instagramm', root_path  %>
        </div>
          <% if user_signed_in? %>
            <ul class="nav navbar-nav navbar-left">
              <li><%= link_to 'Gram It', new_pic_path %></li>
              <li><%= link_to 'Settings', edit_user_registration_path %></li>
              <li><%= link_to 'Sign Out',  destroy_user_session_path, method: :delete %></li>
            </ul>
            <% else %>
              <ul class="nav navbar-nav navbar-left">
                <li><%= link_to 'Join', new_user_registration_path %></li>
                <li><%= link_to 'Sign In', new_user_session_path %></li>
              </ul>
          <% end %>
      </div>
    </nav>

  <div class="container">
    <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: 'alert alert-info') %>
      <% end %>

    <%= yield %>

  </div>
  </body>
</html>

app/views/pics/_form.html.erb
<%= simple_form_for @pic do |f| %>
  <% if @pic.errors.any? %>
    <div id="errors">
      <h2><%= pluralize(@pic.errors.count, 'error') %> prevented this Pic from saving </h2>
      <ul>
        <% @pic.errors.full_messages.each do |msg| %>
          <li> <%= msg %> </li>
        <% end %>
      </ul>
    <div>
  <% end %>

  <div class="form-group">
    <%= f.input :image, as: :file, input_html: { class: 'form_control' } %>
  </div>

  <div class="form-group">
    <%= f.input :title, input_html: { class: 'form_control' } %>
  </div>

  <div class="form-group">
    <%= f.input :description, input_html: { class: 'form_control' } %>
  </div>

  <%= f.button :submit, class:'btn btn-info' %>
<% end %>

app/views/pics/edit.html.erb
<div id="edit_page" class="col-md-8 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">

      <div class="panel-heading">
        <h1> Edit Pic</h1>
      </div>

      <div class="panel-body">
        <div class="current_image">
          <strong>Right Now</strong>
          <%= image_tag @pic.image.url(:medium) %>
        </div>
        <%= render 'form' %>
      </div>

    </div>
  </div>
</div>

app/views/pics/index.html.erb
<div class="col-md-6 col-md-offset-3">
  <div id="pics" class="transitions-enabled">
    <% @pics.each do |pic| %>
      <div class="box panel panel-default">
        <%= link_to (image_tag pic.image.url), pic %>
        <h2> <%= link_to pic.title, pic %></h2>
      </div>
    <% end %>
  </div>
</div>

app/views/pics/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">

      <div class="panel-heading">
        <h1> Post Pic </h1>
      </div>

      <div class="panel-body">
        <%= render 'form' %>
      </div>

    </div>
  </div>
</div>

app/views/pics/show.html.erb
<div id="pic_show" class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">

      <div class="panel heading pic_image">
        <%= image_tag @pic.image.url %>
      </div>

      <div class="panel-body">
        <h1><%= @pic.title %><h1>
        <p><%= @pic.description %></p>
      </div>

      <div class="panel-footer">

        <div class="row">

          <div class="col-md-6">
            <p class="user"><%= @pic.user.email %></p>
          </div>

          <div class="col-md-6">
            <div class="btn-group pull-right">
              <%= link_to like_pic_path(@pic), method: :put, class: 'btn btn-danger' do %>
                  <span class="glyphicon glyphicon-heart"> <span>
                  <%= @pic.get_upvotes.size %>
                <% end %>

                <% if current_user == @pic.user %>
                  <%= link_to 'Edit', edit_pic_path, class: 'btn btn-info' %>
                  <%= link_to 'Delete', pic_path, method: :delete, data: { confirm: 'Are you sure' }, class: 'btn btn-danger' %>
                <% end %>
            <div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>